services:
  - type: web
    name: cardio-backend
    runtime: docker
    rootDir: backend-bayesian
    dockerfilePath: ./Dockerfile
    envVars:
      - key: GEMINI_API_KEY
        sync: false

  - type: web
    name: cardio-frontend
    env: static
    rootDir: frontend-ui
    buildCommand: npm install && npm run build
    staticPublishPath: build
    envVars:
      - key: REACT_APP_API_URL
        sync: false
